### ISSUE TITLE
Change spinner and text when stopping a spinner

### ISSUE THREAD

**Issue by giacomocavalieri** [lpil/spinner#1]
It would be really nice being able to change the text and spinner icon of a spinner when the spinner is stopped. Right now the spinner just stops and it looks like it's hanging since it still shows one of its frames.

I've tried doing:
```gleam
spinner.set_text(spinner, ansi.green("Done!"))
spinner.stop(spinner)
```

But that doesn't change the spinner's text before stopping it. Adding a `process.sleep` before the `stop` call seems to fix it but it feels like a hack, and there's still the problem that I can't change the spinning icon once the spinner was stopped.

```
⠇ Done!
^ I would like the ability to change this to something else, like "✅"
```

**Comment by lpil** [comment]
Good point!

Let's make it print whatever the final text is when stopping, and let's add a function to clear the line so that folks can optionally replace the output with a ✅ or whatever they want.

**Comment by lpil** [comment]
Thank you
