### ISSUE TITLE
[Question]: Thoughts on callback based spinner impl?

### ISSUE THREAD

**Issue by ethanthoma** [lpil/spinner#5]
This somewhat relates to #2 

I was wondering if there could/should be a callback variant of start? 

We can use `use`  for resource management. Something like
```gleam
pub fn start_callback(builder: Builder, context: fn(Spinner) -> a) {
  let spinner = start(builder)

  context(spinner)

  stop(spinner)
}
```

which can be used like so:
```gleam
pub fn main() {
    use spinner <- spinner.start_callback(
      spinner.new("Baking Bread for Toasters")
      |> spinner.with_colour(ansi.cyan),
    )

    process.sleep(1000)
    spinner.set_text(spinner, "Compositing Vampiric Complexions")
    spinner.set_colour(spinner, ansi.pink)
}
```

I'm not sure if this is idiomatic or even encouraged so I would like to get your thoughts on this (if this is an appropriate forum for doing so)!

**Comment by lpil** [comment]
Sounds good! This might be called `with` or `with_spinner`
